theme: jekyll-theme-cayman
title: "GSA/Section 508"
description: "This draft contains guidance for meeting the Revised 508 Standards for Web sites and was created by the ACOP technical workgroup . The purpose was to identify requirements that are the responsibility of a developer and requirements that are more likely to be the responsibility of a site's designer. The ACOP working group wanted to configure guidance so that viewers can find information easily. A listing of WCAG Success Criteria according to criterion number ing (1.2.1, 1.2.2, etc.) was determined to be undesirable."

